tools:
#    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    # php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
filter:
    excluded_paths:
        - 'tests/*'
build:
    environment:
        php:
            version: 7.3
    project_setup:
        before:
            - pecl install zip
